---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[client_wrapper::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
